#!/bin/sh

ARGS="--volume=60"

RADIO_LIST=("Lofi Girl"
            "Chillhop"
            "Box Lofi"
            "The Bootleg Boy"
            "Radio Spinner"
            "SmoothChill")

URL=("https://play.streamafrica.net/lofiradio"
    "http://stream.zeno.fm/fyn8eh3h5f8uv"
    "http://stream.zeno.fm/f3wvbbqmdg8uv"
    "http://stream.zeno.fm/0r0xa792kwzuv"
    "https://live.radiospinner.com/lofi-hip-hop-64"
    "https://media-ssl.musicradio.com/SmoothChill")

notification(){
    notify-send "Playing now: " "$@" --icon=media-tape
}

menu(){
    for ((i=0; i<${#RADIO_LIST[@]}; i++)); do
        printf "$((i+1)). ${RADIO_LIST[$i]}\n"
    done
}

main() {
    choice=$(menu | dmenu -i -l 5 -p "Dmenu-beats" | cut -d' ' -f1 | tr -d '.')
    printf "${RADIO_LIST[$choice-1]}\n"

    if [[ $choice -ge 1 && $choice -le ${#RADIO_LIST[@]} ]]; then
        notification "${RADIO_LIST[$choice-1]} ☕️🎶"
        st -e mpv $ARGS --title="radio-mpv" "${URL[$choice-1]}"
    fi
}

pkill -f radio-mpv || main
